### ISSUE TITLE
Setup logging in multiple modules

### ISSUE THREAD

**Issue by LastStarDust** [pymeasure/pymeasure#748] opened 2022-11-16 02:31 UTC
I initialize the logger in the main module using `pymeasure.log.setup_logging` but the settings are not applied to all other submodules. 
This is what I am doing:
```
--> main.py
|
|--> mod.py
```

`main.py`
```python
import logging
import mod
from pymeasure.log import setup_logging

log = logging.getLogger(__name__)
log.addHandler(logging.NullHandler())

if __name__ == '__main__':
    setup_logging(log, console=True, console_level='DEBUG')
    log.debug("main")
    mod.foo()
```

`mod.py`
```python
import logging
log = logging.getLogger(__name__)

def foo():
    log.debug("mod")
```

Only "main" log is shown to the console, however, in the GUI Experiment Log, all logs are shown. 

**Am I doing something wrong? I would expect that I would need to call `setup_logging` only at the top level.**

**Comment by bilderbuchi** [comment] 2022-11-16 05:39
I am assuming that it's an oversight that you don't call foo() in our MWE, and that's not a factor in the real situation?
In any case, we should take a look at this.

**Comment by bilderbuchi** [comment] 2022-11-19 14:22
I confirmed that replacing the `setup_logging` call with `logging.basicConfig(level=logging.DEBUG)` yields the expected behaviour, so we'll have to find out what the difference in `setup_logging` is.

**Comment by LastStarDust** [comment] 2022-11-19 14:33
@bilderbuchi Do you suggest any patch or workaround for the time being? I am asking because next week, I would like to use my pymeasure-based software at work.

**Comment by bilderbuchi** [comment] 2022-11-19 14:38
Workaround: Use the call `setup_logging(logger=logging.getLogger(), console=True, console_level='DEBUG')` (note different first argument). At least in my current tests this makes the debug messages in `mod` show up.

**Comment by bilderbuchi** [comment] 2022-11-19 15:01
Actually, just leave out the `logger` argument, and everything works as it should! 
Agree to close this?

**Comment by bmoneke** [comment] 2022-11-19 15:06
Ah, I guess I know, where the problem is:
You set the level for the "__main__" logger, which is not the parent of the "foo" logger!

**Comment by LastStarDust** [comment] 2022-11-19 16:30
Thank you for the prompt reply. I verified that by leaving out the logger argument, everything works as expected.

**Comment by bilderbuchi** [comment] 2022-11-19 16:47
Great!

**Closed** 2022-11-19 16:47 UTC
